lab.LocalCosmosDbApp/lab.LocalCosmosDbApp/ViewModels/ErrorViewModel.cs
namespace lab.LocalCosmosDbApp.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lab.LocalCosmosDbApp/lab.LocalCosmosDbApp/Controllers/BusinessUnitToolInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lab.LocalCosmosDbApp.ViewModels;
using Microsoft.Extensions.Logging;
using lab.LocalCosmosDbApp.Managers;
using DataTables.AspNet.Core;
using DataTables.AspNet.AspNetCore;
using lab.LocalCosmosDbApp.Exceptions;
using lab.LocalCosmosDbApp.Helpers;

namespace lab.LocalCosmosDbApp.Controllers
{
    public class BusinessUnitToolInfoController : BaseController
    {
        #region Global Variable Declaration
        private readonly ILogger<BusinessUnitToolInfoController> _logger;
        private static IBusinessUnitToolInfoManager _iBusinessUnitToolInfoManager;
        #endregion

        #region Constructor
        public BusinessUnitToolInfoController(IBusinessUnitToolInfoManager iBusinessUnitToolInfoManager)
        {
            ILoggerFactory loggerFactory = new LoggerFactory();
            _logger = loggerFactory.CreateLogger<BusinessUnitToolInfoController>();
            _iBusinessUnitToolInfoManager = iBusinessUnitToolInfoManager;
        }
        #endregion

        #region Actions

        // GET: BusinessUnitToolInfo
        public async Task<IActionResult> Index()
        {
            try
            {
                //var viewModelList = await _iBusinessUnitToolInfoManager.GetBusinessUnitToolInfosAsync();
                //return View(viewModelList);

                return View("DataTable");
            }
            catch (Exception ex)
            {
                return ErrorView(ex);
            }
        }

        [HttpGet]
        [ResponseCache(NoStore = true, Duration = 0)]
        public async Task<IActionResult> GetDataAjax(IDataTablesRequest request)
        {
            try
            {
                DataTablesResponse response = await _iBusinessUnitToolInfoManager.GetDataTablesResponseAsync(request);
                return new DataTablesJsonResult(response, true);
            }
            catch (Exception ex)
            {
                return ErrorPartialView(ex);
            }
        }

        // GET: BusinessUnitToolInfo/Details/5
        public async Task<IActionResult> Details(string id)
        {
            try
            {
                var viewModel = await _iBusinessUnitToolInfoManager.GetBusinessUnitToolInfoAsync(id);
                if (viewModel == null)
                {
                    return NotFound();
                }

                return View(viewModel);
            }
            catch (Exception ex)
            {
                return ErrorView(ex);
            }
        }

        // GET: BusinessUnitToolInfo/Create
        public IActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                return ErrorView(ex);
            }
        }

        // POST: BusinessUnitToolInfo/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BusinessUnitToolInfoViewModel personViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _iBusinessUnitToolInfoManager.InsertBusinessUnitToolInfoAsync(personViewModel);
                    return RedirectToAction(nameof(Index));
                }
                return View(personViewModel);
            }
            catch (Exception ex)
            {
                return ErrorView(ex);
            }
        }

        // GET: BusinessUnitToolInfo/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            try
            {
                var viewModel = await _iBusinessUnitToolInfoManager.GetBusinessUnitToolInfoAsync(id);
                if (viewModel == null)
                {
                    return NotFound();
                }

                return View(viewModel);
            }
            catch (Exception ex)
            {
                return ErrorView(ex);
            }
        }

        // POST: BusinessUnitToolInfo/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, BusinessUnitToolInfoViewModel personViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _iBusinessUnitToolInfoManager.UpdateBusinessUnitToolInfoAsync(personViewModel);
                    return RedirectToAction(nameof(Index));
                }
                return View(personViewModel);
            }
            catch (Exception ex)
            {
                return ErrorView(ex);
            }
        }

        // GET: BusinessUnitToolInfo/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                var viewModel = await _iBusinessUnitToolInfoManager.GetBusinessUnitToolInfoAsync(id);
                if (viewModel == null)
                {
                    return NotFound();
                }

                return View(viewModel);
            }
            catch (Exception ex)
            {
                return ErrorView(ex);
            }
        }

        // POST: BusinessUnitToolInfo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            try
            {
                var viewModel = await _iBusinessUnitToolInfoManager.GetBusinessUnitToolInfoAsync(id);
                if (viewModel == null)
                {
                    return NotFound();
                }

                await _iBusinessUnitToolInfoManager.DeleteBusinessUnitToolInfoAsync(viewModel.Id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return ErrorView(ex);
            }
        }

        private async Task<bool> BusinessUnitToolInfoViewModelExists(string id)
        {
            var viewModel = await _iBusinessUnitToolInfoManager.GetBusinessUnitToolInfoAsync(id);
            return viewModel != null ? true : false;
        }

        [HttpGet]
        [ResponseCache(NoStore = true, Duration = 0)]
        public async Task<IActionResult> AddAjax()
        {
            try
            {
                var viewModel = new BusinessUnitToolInfoViewModel();
                if (viewModel != null)
                {
                    return PartialView("~/Views/BusinessUnitToolInfo/_AddOrEdit.cshtml", viewModel);
                }
                else
                {
                    return ErrorPartialView(ExceptionHelper.ExceptionErrorMessageForNullObject());
                }
            }
            catch (Exception ex)
            {
                return ErrorPartialView(ex);
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditAjax(string id)
        {
            try
            {
                if (!string.IsNullOrEmpty(id))
                {
                    var viewModel = await _iBusinessUnitToolInfoManager.GetBusinessUnitToolInfoBySqlQueryAsync(id);
                    if (viewModel != null)
                    {
                        //return PartialView("_AddOrEdit", viewModel);
                        return PartialView("~/Views/BusinessUnitToolInfo/_AddOrEdit.cshtml", viewModel);
                    }
                    else
                    {
                        return ErrorPartialView(ExceptionHelper.ExceptionErrorMessageForNullObject());
                    }
                }
                else
                {
                    return ErrorPartialView(ExceptionHelper.ExceptionErrorMessageForNullObject());
                }
            }
            catch (Exception ex)
            {
                return ErrorPartialView(ex);
            }
        }

        [HttpGet]
        public async Task<IActionResult> DetailsAjax(string id)
        {
            try
            {
                if (!string.IsNullOrEmpty(id))
                {
                    var viewModel = await _iBusinessUnitToolInfoManager.GetBusinessUnitToolInfoBySqlQueryAsync(id);
                    if (viewModel != null)
                    {
                        //return PartialView("_Details", viewModel);
                        return PartialView("~/Views/BusinessUnitToolInfo/_Details.cshtml", viewModel);
                    }
                    else
                    {
                        return ErrorPartialView(ExceptionHelper.ExceptionErrorMessageForNullObject());
                    }
                }
                else
                {
                    return ErrorPartialView(ExceptionHelper.ExceptionErrorMessageForNullObject());
                }
            }
            catch (Exception ex)
            {
                return ErrorPartialView(ex);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveAjax(BusinessUnitToolInfoViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (string.IsNullOrEmpty(viewModel.Id)) //add
                    {
                        viewModel.Id = Guid.NewGuid().ToString();
                        _result = await _iBusinessUnitToolInfoManager.InsertBusinessUnitToolInfoAsync(viewModel);
                    }
                    else if (!string.IsNullOrEmpty(viewModel.Id)) //edit
                    {
                        _result = await _iBusinessUnitToolInfoManager.UpdateBusinessUnitToolInfoAsync(viewModel);
                    }
                }
                else
                {
                    _result = Result.Fail(ExceptionHelper.ModelStateErrorFirstFormat(ModelState));

lab.LocalCosmosDbApp/lab.LocalCosmosDbApp/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lab.LocalCosmosDbApp.ViewModels;
using Microsoft.Extensions.Logging;
using lab.LocalCosmosDbApp.Managers;
using DataTables.AspNet.Core;
using DataTables.AspNet.AspNetCore;
using lab.LocalCosmosDbApp.Attributes;

namespace lab.LocalCosmosDbApp.Controllers
{
    //[Authorize]
    //[ServiceFilter(typeof(InitAuthorizeAttribute))]
    public class PersonController : BaseController
    {
        #region Global Variable Declaration
        private readonly ILogger<PersonController> _logger;
        private static IPersonManager _iPersonManager;
        #endregion

        #region Constructor
        public PersonController(IPersonManager iPersonManager)
        {
            ILoggerFactory loggerFactory = new LoggerFactory();
            _logger = loggerFactory.CreateLogger<PersonController>();
            _iPersonManager = iPersonManager;
        }
        #endregion

        #region Actions

        // GET: Person
        public async Task<IActionResult> Index()
        {
            try
            {
                var viewModelList = await _iPersonManager.GetPersonsAsync();
                return View(viewModelList);
            }
            catch (Exception ex)
            {
                return ErrorView(ex);
            }
        }

        [HttpGet]
        [ResponseCache(NoStore = true, Duration = 0)]
        public async Task<IActionResult> GetDataTableDataAjax(IDataTablesRequest request)
        {
            try
            {
                //string currentUserName = Convert.ToString(User?.Identity?.Name);
                //string currentUserRoleName = Convert.ToString(User.FindFirst(ClaimTypes.Role).Value);
                string currentUserName = "admin@mail.com";
                string currentUserRoleName = "admin";
                DataTablesResponse response = await _iPersonManager.GetDataTablesResponseAsync(request, currentUserName, currentUserRoleName);
                return new DataTablesJsonResult(response, true);
            }
            catch (Exception ex)
            {
                return ErrorPartialView(ex);
            }
        }

        // GET: Person/Details/5
        public async Task<IActionResult> Details(string id)
        {
            try
            {
                var viewModel = await _iPersonManager.GetPersonAsync(id);
                if (viewModel == null)
                {
                    return NotFound();
                }

                return View(viewModel);
            }
            catch (Exception ex)
            {
                return ErrorView(ex);
            }
        }

        // GET: Person/Create
        public IActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                return ErrorView(ex);
            }
        }

        // POST: Person/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PersonViewModel personViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _iPersonManager.InsertPersonAsync(personViewModel);
                    return RedirectToAction(nameof(Index));
                }
                return View(personViewModel);
            }
            catch (Exception ex)
            {
                return ErrorView(ex);
            }
        }

        // GET: Person/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            try
            {
                var viewModel = await _iPersonManager.GetPersonAsync(id);
                if (viewModel == null)
                {
                    return NotFound();
                }

                return View(viewModel);
            }
            catch (Exception ex)
            {
                return ErrorView(ex);
            }
        }

        // POST: Person/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, PersonViewModel personViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _iPersonManager.UpdatePersonAsync(personViewModel);
                    return RedirectToAction(nameof(Index));
                }
                return View(personViewModel);
            }
            catch (Exception ex)
            {
                return ErrorView(ex);
            }
        }

        // GET: Person/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                var viewModel = await _iPersonManager.GetPersonAsync(id);
                if (viewModel == null)
                {
                    return NotFound();
                }

                return View(viewModel);
            }
            catch (Exception ex)
            {
                return ErrorView(ex);
            }
        }

        // POST: Person/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            try
            {
                var viewModel = await _iPersonManager.GetPersonAsync(id);
                if (viewModel == null)
                {
                    return NotFound();
                }

                await _iPersonManager.DeletePersonAsync(viewModel.Id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return ErrorView(ex);
            }
        }

        private async Task<bool> PersonViewModelExists(string id)
        {
            var viewModel = await _iPersonManager.GetPersonAsync(id);
            return viewModel != null ? true : false;
        }

        #endregion
    }
}

lab.LocalCosmosDbApp/lab.LocalCosmosDbApp/Views/Shared/_Error.cshtml
@model lab.LocalCosmosDbApp.Exceptions.ErrorPageViewModel
<div id="errorPage">
    <div class="error-page">
        <div class="error-content">
            <h3>
                <i class="fa fa-warning text-yellow"></i>Oops! Something went wrong.
            </h3>
            <p>
                @Model.ErrorMessage
            </p>
        </div>
    </div>
    <!-- /.error-page -->
</div>

lab.LocalCosmosDbApp/lab.LocalCosmosDbApp/Views/Shared/_ErrorModal.cshtml
@model lab.LocalCosmosDbApp.Exceptions.ErrorPageViewModel
<div id="errorPage">
    <div class="error-page">
        <div class="error-content">
            <h3>
                <i class="fa fa-warning text-yellow"></i>Oops! Something went wrong.
            </h3>
            <p>
                @Model.ErrorMessage
            </p>
        </div>
    </div>
    <!-- /.error-page -->
</div>

lab.LocalCosmosDbApp/lab.LocalCosmosDbApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Local CosmosDb App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="~/lib/bootstrap-450/dist/css/bootstrap.css" />*@
    <link rel="stylesheet" href="~/lib/jquery-datatable/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/lib/toastr/css/toastr.css" />
    <link rel="stylesheet" href="~/css/spinners.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Local CosmosDb App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ImportFiles">Import File</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Person</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToolInfoApproverSource" asp-action="Index">Tool Info</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BusinessUnitToolInfo" asp-action="Index">Business Unit</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div id="modalContainer"></div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Local CosmosDb App
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js" type="text/javascript"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    @*<script src="~/lib/bootstrap-450/dist/js/bootstrap.bundle.min.js" type="text/javascript"></script>*@

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
    <script src="~/lib/jquery-datatable/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="~/lib/toastr/js/toastr.min.js" type="text/javascript"></script>

    <!--begin :: application script-->
    <script src="~/js/app/app.js" type="text/javascript"></script>
    <!--end :: application script-->

    <script src="~/js/site.js" asp-append-version="true"></script>

    <script type="text/javascript">
        !(function ($) {
            // preloader
            $(window).on('load', function () {
                if ($('.preloader').length) {
                    $('.preloader').delay(100).fadeOut('slow', function () {
                        //$(this).remove();
                    });
                }
            });
        })(jQuery);
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>